spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
      connection-timeout: 2000
      
  jpa:
    show-sql: true

server:
  port: 8080

#ennable debug mode
debug: true
      
      
      
    