spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
      connection-timeout: 2000
      #MBean (JMX) Monitoring and Management,
      #In order to use JMX, you must set the pool property registerMbeans=true.
      register-mbeans: true
      
#To enable hikari JMX bean, need to disable this. Or will get jmx bean already register exception.
  jmx:
    enabled: false
      
#Keep INFO level in develop prifile
logging:
  level:
    root: INFO
      
  jpa:
    show-sql: false