
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 2
      connection-timeout: 2000
      #MBean (JMX) Monitoring and Management,
      #In order to use JMX, you must set the pool property registerMbeans=true.
      register-mbeans: true
      pool-name: myHikari
      
  kafka:
    bootstrap-servers:
      - localhost: 9092
    consumer:
      group-id: myKafkaGroup
    template:
      default-topic: myTopic
    listener:
      concurrency: 3
    producer:
      batch-size: 1000
      
  jpa:
    show-sql: true
#To enable hikari JMX bean, need to disable this. Or will get jmx bean already register exception.
  jmx:
    enabled: false
    
#Keep DEBUG level in develop prifile
logging:
  level:
    root: INFO
    
#ennable debug mode
#debug: true

server:
#context path
  context-path: /myboot
  
#Full authentication is required to access actuator endpoints.
#add spring security or disable security
management:
  security:
    enabled: false
